More practical self-packaged Vim w/ monthly update

diff --git a/home/bin/update-vim b/home/bin/update-vim
--- a/home/bin/update-vim
+++ b/home/bin/update-vim
@@ -1,9 +1,18 @@
 #! /bin/sh -e
 
+readonly dir=$XDG_CACHE_HOME/${0##*/}
+if [ ! -d "$dir/.git" ]; then
+    git clone --depth=1 --single-branch --branch=master --no-tags \
+        https://github.com/vim/vim.git "$dir"
+fi
+cd "$dir"
+git fetch --depth=1 --no-tags upstream master
+git reset --hard FETCH_HEAD
+
 if ! head -n1 README.txt 2>/dev/null |
     grep -q '^README.txt for version [[:digit:]].[[:digit:]] of Vim: Vi IMproved.$'
 then
-    echo >&2 'Navigate to the correct directory.'
+    echo >&2 'Invalid Vim checkout.'
     exit 2
 fi
 
@@ -39,5 +48,9 @@ fi
     --without-gnome                                              \
     --without-x
 
-make -j8
-sudo make install
+if [ "$1" = "uninstall" ]; then
+    sudo make uninstall
+else
+    make -j8
+    sudo make install
+fi
